config/routes.rb
Sharebox::Application.routes.draw do

  resources :folders
  match "browse/:folder_id" => "home#browse", :as => "browse"
  
  match "browse/:folder_id/new_folder" => "folders#new", :as => "new_sub_folder"
  
  match "browse/:folder_id/new_file" => "packets#new", :as => "new_sub_file"
  resources :packets

  match "browse/:folder_id/rename" => "folders#edit", :as => "rename_folder"  

  match "packets/get/:id" => "packets#get", :as => "download"

  get "home/index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end
  root :to => "home#index"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index  
    if user_signed_in?  
       #show only root folders (which have no parent folders)  
       @folders = current_user.folders.roots   

       #show only root files which has no "folder_id"  
       @packets = current_user.packets.where("folder_id is NULL").order("uploaded_file_file_name desc")        
    end  
  end
  #this action is for viewing folders  
  def browse  
      #get the folders owned/created by the current_user  
      @current_folder = current_user.folders.find(params[:folder_id])    

      if @current_folder  

        #getting the folders which are inside this @current_folder  
        @folders = @current_folder.children  

        #show only files under this current folder  
        @packets = @current_folder.packets.order("uploaded_file_file_name desc")
        
        #We need to fix this to show files under a specific folder if we are viewing that folder  
        @packets = current_user.packets.order("uploaded_file_file_name desc")  

        render :action => "index"  
      else  
        flash[:error] = "Don't be cheeky! Mind your own folders!"  
        redirect_to root_url  
      end  
  end  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_breadcrumbs.html.erb
<div class="breadcrumbs">          
    <% if @current_folder #checking if we are under any folder %>  
        <%= link_to "Simple Share", root_url %>  
        <% @current_folder.ancestors.reverse.each do |folder| %>  
            » <%= link_to folder.name, browse_path(folder) %>  
        <% end %>  
         »  <%= @current_folder.name %>  
    <% else #if we are not under any folder%>  
        Simple Share
    <% end %>  
</div>

app/views/home/index.html.erb
<% unless user_signed_in? %>  
    <h1>Welcome to ShareBox</h1>  
    <p>File sharing web application you can't ignore.</p>  
      
<% else %>  
    <div id="menu">  
        <%= render :partial => "breadcrumbs" %>
       <ul id= "top_menu">      
           <ul id= "top_menu">      
                 <% if @current_folder %>  
                  <li><%= link_to "Upload", new_sub_file_path(@current_folder) %></li>  
                  <li><%= link_to "New Folder", new_sub_folder_path(@current_folder) %></li>  
              <% else %>  
                  <li><%= link_to "Upload", new_packet_path %></li>  
                  <li><%= link_to "New Folder", new_folder_path %></li>  
              <% end %>  
           </ul>
       </ul>  
    </div> 
  
   <div class="asset_list_header">  
       <div class="file_name_header">File Name</div>  
       <div class="file_size_header">Size</div>  
       <div class="file_last_updated_header">Modified</div>  
   </div>  
   <div class="clear"></div>
   <div class="packet_list">  
       <!-- Listing Folders -->  
       <% @folders.each do |folder| %>  
            <div class="asset_details folder">  
               <div class="file_name"><%= link_to folder.name, browse_path(folder) %></div>  
               <div class="file_size">-</div>  
               <div class="file_last_updated">-</div>  
               <div class="actions">  
                   <div class="share">  
                       <%= link_to "Share" %>  
                   </div>  
                   <div class="rename">  
                       <%= link_to "Rename", rename_folder_path(folder) %>  
                   </div>  
                   <div class="delete">  
                     <%= link_to "Delete", folder, :confirm => 'Are you sure to delete the folder and all of its contents?', :method => :delete %>    
                   </div>  
               </div>  
           </div>  
       <% end %> 

       <!-- Listing Files -->  
         <% @packets.each do |packet| %>  
             <div class="packet_details file">  
                 <div class="file_name"><%= link_to packet.file_name, download_url(packet) %></div>  
                 <div class="file_size"><%= number_to_human_size(packet.file_size, :precision => 2) %></div>  
                 <div class="file_last_updated"><%= packet.uploaded_file_updated_at %></div>  
                 <div class="actions">  
                    <div class="download">  
                    <%= link_to "Download", download_url(packet) %>  
                    </div>  
                    <div class="delete">  
                        <%= link_to "Delete", packet, :confirm => 'Are you sure?', :method => :delete %>  
                     
                    </div>  
                </div>
             </div>  
         <% end %>  
   </div>
<% end %>