config/routes.rb
Sharebox::Application.routes.draw do

  resources :folders
  match "browse/:folder_id" => "home#browse", :as => "browse"
  
  match "browse/:folder_id/new_folder" => "folders#new", :as => "new_sub_folder"
  
  match "browse/:folder_id/new_file" => "packets#new", :as => "new_sub_file"
  resources :packets

  match "browse/:folder_id/rename" => "folders#edit", :as => "rename_folder"  

  match "packets/get/:id" => "packets#get", :as => "download"

  get "home/index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end
  root :to => "home#index"

end

app/models/packet.rb
class Packet < ActiveRecord::Base
  
  

 
  def file_size  
      uploaded_file_file_size  
  end
  
  def file_name  
      uploaded_file_file_name  
  end
  
  attr_accessible :user_id, :uploaded_file, :folder_id  
  
  belongs_to :user
  belongs_to :folder
  
  #set up "uploaded_file" field as attached_file (using Paperclip)  
  has_attached_file :uploaded_file  

  validates_attachment_size :uploaded_file, :less_than => 30.megabytes    
  validates_attachment_presence :uploaded_file
end

app/controllers/packets_controller.rb
class PacketsController < ApplicationController
  def index
    @packets = current_user.packets.all
  end

  def show
    @packet = current_user.packets.find(params[:id])
  end

  def new  
    @packet = current_user.packets.build      
    if params[:folder_id] #if we want to upload a file inside another folder  
     @current_folder = current_user.folders.find(params[:folder_id])  
     @packet.folder_id = @current_folder.id  
    end      
  end

  def create  

    @packet = current_user.packets.build(params[:packet])  
    if @packet.save  
     flash[:notice] = "Successfully uploaded the file."  

     if @packet.folder #checking if we have a parent folder for this file  
       redirect_to browse_path(@packet.folder)  #then we redirect to the parent folder  
     else  
       redirect_to root_url  
     end        
    else  
     render :action => 'new'  
    end  
  end  


  def edit
    @packet = current_user.packets.find(params[:id])
  end

  def update
    @packet = current_user.packets.find(params[:id])
    if @packet.update_attributes(params[:packet])
      redirect_to @packet, :notice  => "Successfully updated packet."
    else
      render :action => 'edit'
    end
  end

  def destroy  
    @packet = current_user.packets.find(params[:id])  
    @parent_folder = @packet.folder #grabbing the parent folder before deleting the record  
    @packet.destroy  
    flash[:notice] = "Successfully deleted the file."  

    #redirect to a relevant path depending on the parent folder  
    if @parent_folder  
     redirect_to browse_path(@parent_folder)  
    else  
     redirect_to root_url  
    end  
  end
end

app/helpers/packets_helper.rb
module PacketsHelper
end

app/views/packets/_form.html.erb
<%= form_for @packet, :html => {:multipart => true} do |f| %>  
 <%= f.error_messages %>  
  
   <p>  
       <%= f.label :uploaded_file, "File" %><br>  
       <%= f.file_field :uploaded_file %>  
     </p>  
       <%= f.hidden_field :folder_id %>  
 <p><%= f.submit "Upload" %></p>  
<% end %>

app/views/packets/edit.html.erb
<% title "Edit Packet" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @packet %> |
  <%= link_to "View All", packets_path %>
</p>

app/views/packets/index.html.erb
<% title "Packets" %>

<table>
  <tr>
    <th>User</th>
  </tr>
  <% for packet in @packets %>
    <tr>
      <td><%= packet.user_id %></td>
      <td><%= link_to packet.file_name, download_url(packet) %></td>
      <td><%= link_to "Show", packet %></td>
      <td><%= link_to "Edit", edit_packet_path(packet) %></td>
      <td><%= link_to "Destroy", packet, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Packet", new_packet_path %></p>

app/views/packets/new.html.erb
<% title "Upload a file" %>  
<%= render :partial => "home/breadcrumbs" %>  
  
<%= render 'form' %>  
  
<p>  
<% if @packet.folder %>  
   <%= link_to "Back to '#{@packet.folder.name}' Folder", browse_path(@packet.folder) %>  
<% else %>  
   <%= link_to "Back", root_url %>  
<% end %>  
</p>  

app/views/packets/show.html.erb
<% title "Packet" %>

<p>
  <strong>User:</strong>
  <%= @packet.user_id %>
</p>

<p>
  <%= link_to "Edit", edit_packet_path(@packet) %> |
  <%= link_to "Destroy", @packet, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", packets_path %>
</p>